# This will both tag the git repository and build a docker image with the 
# same version as the git tag on each push to master
name: Versioned Docker CI v2

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Git Checkout
        id: git_checkout
        uses: actions/checkout@v2
        with:
          # Fetches entire history, so we can analyze commits since last tag
          fetch-depth: 0

      - name: Bump version and push tag
        uses: mathieudutour/github-tag-action@v4.5
        with:
          # Required for permission to tag the repo; GitHub automatically
          # creates a GITHUB_TOKEN secret to use in your workflow
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: patch # other options are minor and major
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          # Preferably, use a dockerhub service account user
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Publish Docker Image
        id: docker_publish
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            tessthyer/${{ github.event.repository.name }}:latest-versioned-docker-build
            tessthyer/${{ github.event.repository.name }}:${{ steps.calc_version.outputs.new_version }}-versioned-docker-build
