# This workflow is only triggered when tags are pushed manually (i.e., not
# from within another workflow). This will build a docker image tagged with
# the same version as the git tag just pushed.
name: Manual Tag CI

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Git Checkout
        id: git_checkout
        uses: actions/checkout@v2

      - name: Set Version
        id: new_version
        run: |
          new_version=${GITHUB_REF#"refs/tags/v"}
          echo "::set-env name=NEW_VERSION::$new_version"
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          # Preferably, use a dockerhub service account user
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Publish Docker Image
        id: docker_publish
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            tessthyer/${{ github.event.repository.name }}:${{ env.NEW_VERSION }}-git-tag-triggered-docker-build
