name: Docker CI v1

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Git Checkout
        id: git_checkout
        uses: actions/checkout@v2

      - name: Publish Docker Image
        id: docker_publish
        uses: docker/build-push-action@v1
        with:
          repository: tessthyer/${{ github.event.repository.name }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: latest-simple-docker-build-v1
